# Generated by Django 5.1.5 on 2025-01-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_comment_is_negative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_negative',
            field=models.BooleanField(default=False),
        ),
    ]
